### ISSUE TITLE
[searchguard] IndexNotFoundException[no such index]

### ISSUE THREAD

**Issue by sikelong123** [desp0916/InstallSearchGuard#1]
问题1：启动es时候出现此问题
[2016-05-10 20:40:48,807][DEBUG][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [bg1] Bound http to address {[::]:9200}
[2016-05-10 20:40:48,809][INFO ][http                     ] [bg1] publish_address {10.0.37.80:9200}, bound_addresses {[::]:9200}
[2016-05-10 20:40:48,809][INFO ][node                     ] [bg1] started
[2016-05-10 20:40:48,829][INFO ][license.plugin.core      ] [bg1] license [bca611f8-2c52-474b-8ca4-ff6c20c32328] - valid
[2016-05-10 20:40:48,833][ERROR][license.plugin.core      ] [bg1] 
# 
# License will expire on [Thursday, June 09, 2016]. If you have a new license, please update it.
# Otherwise, please reach out to your support contact.
# 

[2016-05-10 20:40:48,855][INFO ][gateway                  ] [bg1] recovered [0] indices into cluster_state
[searchguard] IndexNotFoundException[no such index]
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:69)
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:42)
    at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:172)
    at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:120)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.client.support.AbstractClient.multiGet(AbstractClient.java:567)
    at com.floragunn.searchguard.configuration.ConfigurationLoader.load(ConfigurationLoader.java:70)
    at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction$1$1.run(TransportConfigUpdateAction.java:86)
    at java.lang.Thread.run(Thread.java:745)
[searchguard] IndexNotFoundException[no such index]
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:69)
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:42)
    at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:172)
    at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:120)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.client.support.AbstractClient.multiGet(AbstractClient.java:567)
    at com.floragunn.searchguard.configuration.ConfigurationLoader.load(ConfigurationLoader.java:70)
    at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction$1$1.run(TransportConfigUpdateAction.java:86)
    at java.lang.Thread.run(Thread.java:745)
[searchguard] IndexNotFoundException[no such index]
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:69)
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:42)
    at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:172)
    at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:120)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.client.support.AbstractClient.multiGet(AbstractClient.java:567)
    at com.floragunn.searchguard.configuration.ConfigurationLoader.load(ConfigurationLoader.java:70)
    at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction$1$1.run(TransportConfigUpdateAction.java:86)
    at java.lang.Thread.run(Thread.java:745)
[searchguard] IndexNotFoundException[no such index]
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:69)
    at org.elasticsearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:42)
    at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:172)
    at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:120)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.client.support.AbstractClient.multiGet(AbstractClient.java:567)
    at com.floragunn.searchguard.configuration.ConfigurationLoader.load(ConfigurationLoader.java:70)
    at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction$1$1.run(TransportConfigUpdateAction.java:86)
    at java.lang.Thread.run(Thread.java:745)

问题2：添加索引时报错
 es-node1$sudo plugins/search-guard-2/tools/sgadmin.sh   -cd plugins/search-guard-2/sgconfig     -ks sg_scripts/node-bg1-keystore.jks       -ts sg_scripts/truststore.jks           -kspass changeit -tspass changeit           -nhnv -nrhn
Password:
Connect to localhost:9300
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
    at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
    at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
    at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
    at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
    at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:137)

请问这是怎么回事？希望您看到的话帮忙一下。谢谢。

**Comment by chiangandy** [comment]
search guard內定ˋ安裝是enterprise試用版，它有日期限制～日期到就要license，如果要用Community edition, 要在config/elasticsearch.yml中加入
searchguard.enterprise_modules_enabled: false
然後重新啟動，就好了～
只是很多功能都會被拿掉～
